export const COUNTRY_CURRENCIES: { [key: string]: string } = {
  'US': '$',
  'USA': '$',
  'United States': '$',
  'Canada': 'CA$',
  'CA': 'CA$',
  'UK': '£',
  'United Kingdom': '£',
  'GB': '£',
  'EU': '€',
  'Germany': '€',
  'France': '€',
  'Italy': '€',
  'Spain': '€',
  'Netherlands': '€',
  'Belgium': '€',
  'Austria': '€',
  'Portugal': '€',
  'Greece': '€',
  'Ireland': '€',
  'Japan': '¥',
  'JP': '¥',
  'China': '¥',
  'CN': '¥',
  'India': '₹',
  'IN': '₹',
  'Australia': 'A$',
  'AU': 'A$',
  'New Zealand': 'NZ$',
  'NZ': 'NZ$',
  'Switzerland': 'CHF',
  'CH': 'CHF',
  'Sweden': 'kr',
  'SE': 'kr',
  'Norway': 'kr',
  'NO': 'kr',
  'Denmark': 'kr',
  'DK': 'kr',
  'Mexico': 'MX$',
  'MX': 'MX$',
  'Brazil': 'R$',
  'BR': 'R$',
  'South Korea': '₩',
  'KR': '₩',
  'Singapore': 'S$',
  'SG': 'S$',
  'Hong Kong': 'HK$',
  'HK': 'HK$',
  'Thailand': '฿',
  'TH': '฿',
  'Malaysia': 'RM',
  'MY': 'RM',
  'Indonesia': 'Rp',
  'ID': 'Rp',
  'Philippines': '₱',
  'PH': '₱',
  'Vietnam': '₫',
  'VN': '₫',
  'Turkey': '₺',
  'TR': '₺',
  'Russia': '₽',
  'RU': '₽',
  'Poland': 'zł',
  'PL': 'zł',
  'Czech Republic': 'Kč',
  'CZ': 'Kč',
  'Hungary': 'Ft',
  'HU': 'Ft',
  'South Africa': 'R',
  'ZA': 'R',
  'Israel': '₪',
  'IL': '₪',
  'UAE': 'AED',
  'AE': 'AED',
  'Saudi Arabia': 'SAR',
  'SA': 'SAR',
};

export function getCurrencyFromAddress(address: string): string {
  if (!address) return '$';
  
  const addressLower = address.toLowerCase();
  
  for (const [country, currency] of Object.entries(COUNTRY_CURRENCIES)) {
    if (addressLower.includes(country.toLowerCase())) {
      return currency;
    }
  }
  
  return '$';
}
