import { StyleSheet, Platform } from 'react-native';

export const postMealColors = {
  primary: '#FF6B35',
  text: '#2C2C2C',
  textLight: '#666666',
  background: '#FFFFFF',
  surface: '#F8F8F8',
  success: '#4CAF50',
  warning: '#FFA726',
  premium: '#FF6600',
} as const;

export const postMealStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: postMealColors.background,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    paddingVertical: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: postMealColors.text,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 16,
    color: postMealColors.textLight,
    lineHeight: 22,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: postMealColors.text,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 16,
    color: postMealColors.textLight,
    textAlign: 'center',
    lineHeight: 22,
  },
  eventsContainer: {
    gap: 16,
    marginBottom: 24,
  },
  eventCard: {
    backgroundColor: postMealColors.surface,
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  eventImage: {
    width: '100%',
    height: 120,
    resizeMode: 'cover',
  },
  eventContent: {
    padding: 16,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: postMealColors.text,
    flex: 1,
    marginRight: 12,
  },
  profileContainer: {
    flex: 1,
    marginRight: 12,
  },
  profileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: postMealColors.surface,
  },
  clickableName: {
    color: postMealColors.primary,
  },
  nameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mealCountBadge: {
    backgroundColor: '#FFE5CC',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  mealCountText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FF6B35',
  },
  matchIcon: {
    padding: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
    gap: 8,
  },
  eventTypeTag: {
    backgroundColor: postMealColors.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  eventTypeText: {
    fontSize: 12,
    fontWeight: '600',
    color: postMealColors.background,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: postMealColors.surface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: postMealColors.textLight,
  },
  timerText: {
    fontSize: 11,
    fontWeight: '600',
    color: postMealColors.textLight,
  },
  expiredTimer: {
    backgroundColor: '#FFE5E5',
    borderColor: '#FF4444',
  },
  expiredTimerText: {
    color: '#FF4444',
  },
  choiceMadeTimer: {
    backgroundColor: '#FFF3E0',
    borderColor: '#FFA726',
  },
  choiceMadeTimerText: {
    color: '#FFA726',
  },
  detailsToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: postMealColors.background,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    gap: 6,
    marginBottom: 4,
  },
  detailsToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: postMealColors.textLight,
  },
  eventDetails: {
    gap: 8,
    marginBottom: 16,
    paddingTop: 4,
  },
  eventDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eventDetailText: {
    fontSize: 14,
    color: postMealColors.textLight,
    flex: 1,
  },
  choicesContainer: {
    gap: 8,
    marginTop: 12,
  },
  choiceButton: {
    backgroundColor: postMealColors.background,
    borderWidth: 1,
    borderColor: postMealColors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  choiceButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: postMealColors.primary,
    marginBottom: 2,
  },
  choiceSubtext: {
    fontSize: 12,
    color: postMealColors.textLight,
  },
  groupActionContainer: {
    marginTop: 12,
    backgroundColor: postMealColors.background,
    borderWidth: 1,
    borderColor: postMealColors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  groupActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  groupActionText: {
    fontSize: 14,
    fontWeight: '500',
    color: postMealColors.primary,
    flex: 1,
    marginRight: 8,
  },
  infoSection: {
    backgroundColor: postMealColors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.text,
    marginBottom: 8,
  },
  infoText: {
    fontSize: 14,
    color: postMealColors.textLight,
    marginBottom: 4,
    lineHeight: 20,
  },
  dateChoiceSection: {
    gap: 12,
  },
  dateChoiceHeader: {
    marginBottom: 4,
  },
  dateChoiceHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dateChoiceText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  noDecisionContainer: {
    backgroundColor: postMealColors.surface,
    borderWidth: 1,
    borderColor: postMealColors.textLight,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  noDecisionText: {
    fontSize: 14,
    fontWeight: '500',
    color: postMealColors.textLight,
  },
  upgradePromptInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: postMealColors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: postMealColors.premium,
  },
  upgradeTextInline: {
    fontSize: 12,
    color: postMealColors.premium,
    textAlign: 'center',
    fontWeight: '500',
  },
  selectedChoice: {
    backgroundColor: '#FFFFFF',
    borderColor: '#000000',
    borderWidth: 2,
  },
  selectedChoiceText: {
    color: '#000000',
  },
  selectedChoiceSubtext: {
    color: '#000000',
    opacity: 0.8,
  },
  upgradePrompt: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: postMealColors.surface,
    borderRadius: 8,
    marginTop: 8,
  },
  upgradeText: {
    fontSize: 12,
    color: postMealColors.textLight,
    textAlign: 'center',
  },
  userChoicesSection: {
    gap: 8,
    marginTop: 16,
  },
  userChoicesTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  blurredText: {
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
    color: 'transparent',
  },
  blurredChoiceContainer: {
    position: 'relative',
  },
  blurredChoiceText: {
    ...Platform.select({
      web: {
        filter: 'blur(8px)',
      },
      default: {
        opacity: 0.3,
      },
    }),
  },
  blurOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  payToViewButton: {
    backgroundColor: postMealColors.premium,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  payToViewButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: postMealColors.background,
    marginBottom: 2,
  },
  payToViewSubtext: {
    fontSize: 11,
    fontWeight: '500',
    color: postMealColors.background,
    opacity: 0.9,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: postMealColors.background,
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: postMealColors.text,
  },
  closeButton: {
    padding: 4,
  },
  modalDescription: {
    fontSize: 16,
    color: postMealColors.textLight,
    lineHeight: 22,
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: postMealColors.textLight,
    alignItems: 'center',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.textLight,
  },
  upgradeButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: postMealColors.premium,
    alignItems: 'center',
  },
  upgradeButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.background,
  },
  disabledContainer: {
    opacity: 0.5,
  },
  disabledText: {
    color: postMealColors.textLight,
  },
  selectedChoiceButton: {
    backgroundColor: postMealColors.primary,
    borderColor: postMealColors.primary,
  },
  selectedChoiceButtonText: {
    color: postMealColors.background,
  },
  matchModalContent: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  matchIconContainer: {
    position: 'relative',
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallHeart: {
    position: 'absolute',
    top: -10,
    right: -15,
  },
  takenIconContainer: {
    marginBottom: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  takenIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: postMealColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: postMealColors.background,
  },
  takenIconText: {
    fontSize: 36,
    fontWeight: '700',
    color: postMealColors.background,
  },
  noMatchEmoji: {
    fontSize: 60,
    marginBottom: 24,
  },
  matchModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: postMealColors.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  matchModalDescription: {
    fontSize: 16,
    color: postMealColors.textLight,
    lineHeight: 22,
    marginBottom: 32,
    textAlign: 'center',
  },
  noMatchButton: {
    backgroundColor: postMealColors.textLight,
  },
  noMatchButtonText: {
    color: postMealColors.background,
  },
  chatButton: {
    backgroundColor: postMealColors.primary,
  },
  balloonsContainer: {
    position: 'absolute',
    bottom: 100,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 50,
  },
  balloon: {
    fontSize: 40,
  },
  matchModalCloseButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 4,
    zIndex: 1,
  },
  finalizedChoiceButton: {
    backgroundColor: postMealColors.success,
    borderColor: postMealColors.success,
    position: 'relative',
  },
  finalizedChoiceText: {
    color: postMealColors.background,
  },
  finalizedLabel: {
    position: 'absolute',
    top: -8,
    right: 8,
    backgroundColor: postMealColors.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    fontSize: 10,
    fontWeight: '600',
    color: '#FF5C00',
  },
  finalizedBuddyPassButton: {
    backgroundColor: '#FF5C00',
    borderColor: '#FF5C00',
    position: 'relative',
  },
  finalizedBuddyPassLabel: {
    color: '#FF5C00',
  },
  matchPermanentTimer: {
    backgroundColor: '#E8F5E8',
    borderColor: postMealColors.success,
  },
  matchPermanentTimerText: {
    color: postMealColors.success,
  },
  matchIndicator: {
    backgroundColor: '#FFE5CC',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  matchIndicatorText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#FF6B35',
  },
  loveIconContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeIconButton: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: postMealColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  mixedSignalsTimer: {
    backgroundColor: '#FFF0E6',
    borderColor: '#FF6B35',
  },
  mixedSignalsTimerText: {
    color: '#FF6B35',
  },
  retakeDecisionHeader: {
    backgroundColor: '#FFF0E6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#FF6B35',
  },
  retakeDecisionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FF6B35',
    marginBottom: 8,
    textAlign: 'center',
  },
  retakeDecisionSubtitle: {
    fontSize: 14,
    color: '#B8860B',
    lineHeight: 20,
    textAlign: 'center',
  },
  lastChanceText: {
    fontSize: 14,
    color: '#FF4444',
    fontWeight: '700',
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 8,
  },
  disabledChoiceButton: {
    backgroundColor: '#F5F5F5',
    borderColor: '#E0E0E0',
    opacity: 0.6,
  },
  disabledChoiceText: {
    color: '#999999',
  },
  disabledReasonText: {
    fontSize: 11,
    color: '#FF6B35',
    fontStyle: 'italic',
    marginTop: 4,
  },
  tipButtonsContainer: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  noThanksButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: postMealColors.textLight,
    alignItems: 'center',
    backgroundColor: postMealColors.background,
  },
  noThanksButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.textLight,
  },
  dropTipButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: postMealColors.premium,
    alignItems: 'center',
  },
  dropTipButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: postMealColors.background,
  },
  tabsContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    backgroundColor: postMealColors.surface,
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: postMealColors.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: postMealColors.textLight,
  },
  activeTabText: {
    color: postMealColors.background,
  },
});
